# Features which are to be available on the target system.
#
# This dictionary influences
#
# * which packages will be installed to the target system;
# * which plugins will be installed for the software;
# * which parts of configurations are useful/useless on the target system.
features:
  cli:
    - 'extras'
  dev:
    - 'base'
    - 'extras'
    - 'rust'
    - 'java'
    - 'golang'
    - 'haskell'

  gui:
    - 'openbox'

# Facts about the target system which are not gathered by Ansible.
#
# These facts are used to tune the software configurations.
system:
  hidpi: true

# Install packages on target machine?
#
# If false, only configuration files are deployed, so that privileges
# escalation is not required.
install_packages: true

# GOPATH value; relative to user's home directory.
golang_gopath: 'pub/src/misc/gopath'

# A list of vim plugins to install.
vim_plugins:
  - 'youarehere'
  - 'nerdtree'
  - 'syntastic'
  - 'fugitive'
  - 'mru'
  - 'fzf'
  - 'rust'
  - 'rustdoc'
  - 'youcompleteme'
