# Facts about the target system which are not gathered by Ansible.
#
# These facts are used to tune the software configurations.
system:
  hidpi: true

# Install packages on target machine?
#
# If false, only configuration files are deployed, so that privileges
# escalation is not required.
install_packages: true

# A list of vim plugins to install.
vim_plugins:
  - 'nerdtree'
  - 'syntastic'
  - 'fugitive'
  - 'mru'
  - 'rust'
  - 'rustdoc'
  - 'commandt'
  - 'youcompleteme'
