ansible_connection: 'local'

user_config:
  name: 'qazer'
  home_dir: '/home/qazer'
  downloads_dir: '/home/qazer/misc/downloads'

  profile_dropins_dir: '.profile.d'

  shells:
    bash:
      dropins_dir: '.bashrc.d'

  editors:
    vim:
      default: true

  gui:
    de: 'openbox-qaztom'

# Features which are to be available on the target system.
#
# This dictionary influences
#
# * which packages will be installed to the target system;
# * which plugins will be installed for the software;
# * which parts of configurations are useful/useless on the target system.
features:
  cli:
    - 'extras'
  dev:
    - 'base'
    - 'extras'
    - 'rust'
    - 'java'
    - 'golang'
    - 'haskell'

# Install packages on target machine?
#
# If false, only configuration files are deployed, so that privileges
# escalation is not required.
install_packages: true

# GOPATH value; relative to user's home directory.
golang_gopath: 'pub/src/misc/gopath'

ssh:
  use_agent: true

doublecmd:
  terminal: 'alacritty'
  editor: 'subl'

# A list of vim plugins to install.
vim_plugins:
  - 'youarehere'
  - 'nerdtree'
  - 'syntastic'
  - 'fugitive'
  - 'mru'
  - 'fzf'
  - 'rust'
  - 'rustdoc'
  - 'youcompleteme'
