---
- name: 'Fail if role does not support target OS'
  when: 'ansible_os_family not in ["Archlinux"]'
  tags: 'user'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      target OS family is: {{ ansible_os_family }}.

- name: 'Install golang toolchain'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    name: 'go'
    state: 'present'

- name: 'Ensure GOPATH exists'
  tags: 'user'
  ansible.builtin.file:
    path: '{{ user_config.home_dir }}/{{ toolchain_config.gopath }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: 'directory'
    mode: '0755'

- name: 'Install templated profile drop-ins'
  tags: 'user'
  loop:
    - '15_01_go_gopath'
  ansible.builtin.template:
    src: 'profile_dropins/{{ item }}.j2'
    dest: '{{ user_config.home_dir }}/{{ user_config.profile_dropins_dir }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'
