---
- name: 'clean managed drop-ins directory'
  file:
    path: '{{ user_config["home_dir"] }}/.profile.d'
    state: 'absent'

- name: 'ensure drop-ins directories exist'
  loop:
    - '.profile.d'
    - '.profile.d-unmanaged'
  file:
    path: '{{ user_config["home_dir"] }}/{{ item }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755

- name: 'install basic .profile'
  template:
    src: 'profile.j2'
    dest: '{{ user_config["home_dir"] }}/.profile'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
