---
- name: 'install tilda'
  when: 'install_packages'
  become: true
  package:
    name: 'tilda'
    state: 'present'

- name: 'ensure tilda config directory exists'
  file:
    path: '{{ user_config["home_dir"] }}/.config/tilda'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755

- name: 'install tilda config'
  copy:
    src: 'config_0'
    dest: '{{ user_config["home_dir"] }}/.config/tilda/config_0'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
