---
- name: 'install gtk'
  when: 'install_packages'
  become: true
  package:
    name:
      - 'gtk2'
      - 'gtk3'
      - 'gnome-themes-extra'
    state: 'present'

- name: 'install .gtkrc-2.0'
  copy:
    src: 'gtkrc-2.0'
    dest: '{{ user_config["home_dir"] }}/.gtkrc-2.0'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- name: 'ensure gkt3 config directory exists'
  file:
    path: '{{ user_config["home_dir"] }}/.config/gtk-3.0'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755

- name: 'install gtk3 configuration'
  copy:
    src: 'gtk.css'
    dest: '{{ user_config["home_dir"] }}/.config/gtk-3.0/gtk.css'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
