---
- name: 'install gmrun'
  when: 'install_packages'
  become: true
  package:
    name: 'gmrun'
    state: 'present'

- name: 'get home dir of {{ user }}'
  getent:
    database: 'passwd'
    key: '{{ user }}'
    split: ':'

- name: 'store home dir of {{ user }}'
  set_fact:
    home_dir: '{{ getent_passwd[user][4] }}'

- name: 'install gmrun config'
  copy:
    src: 'gmrunrc'
    dest: '{{ home_dir }}/.gmrunrc'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644
