---
# XXX: this role is a stub serving as a feature-flag for legacy systems which
# still have desktop Skype present. For new installations, nothing gets
# installed, as web-version is the preferred alternative.

- name: 'Check that role supports target OS'
  when: 'ansible_os_family not in ["Archlinux"]'
  tags: 'user'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      Target OS family is: {{ ansible_os_family }}.

- name: 'Print stub message'
  tags: 'user'
  ansible.builtin.debug:
    msg: >-
      WARNING: Skype is no longer shipped via official
      Arch repos or via AUR, as MS chose to provide
      only Snap builds since 2023.
