---
- name: 'get home dir of {{ user }}'
  getent:
    database: 'passwd'
    key: '{{ user }}'
    split: ':'

- name: 'store home dir of {{ user }}'
  set_fact:
    home_dir: '{{ getent_passwd[user][4] }}'

- name: 'install .profile'
  template:
    src: 'profile'
    dest: '{{ home_dir }}/.profile'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644
