---
- name: 'Clean managed drop-ins directory'
  tags: 'user'
  ansible.builtin.file:
    path: '{{ user_config["home_dir"] }}/{{ user_config["profile_dropins_dir"] }}'
    state: 'absent'
  when: 'clean_configs in ["safe", "all"]'

- name: 'Ensure drop-ins directories exist'
  tags: 'user'
  ansible.builtin.file:
    path: '{{ user_config["home_dir"] }}/{{ user_config["profile_dropins_dir"] }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: 'directory'
    mode: '0755'

- name: 'Install basic .profile'
  tags: 'user'
  ansible.builtin.template:
    src: 'profile.j2'
    dest: '{{ user_config["home_dir"] }}/.profile'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'

- name: 'Install basic drop-ins'
  tags: 'user'
  ansible.builtin.copy:
    src: 'dropins/'
    dest: '{{ user_config["home_dir"] }}/{{ user_config["profile_dropins_dir"] }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'
