---
- name: 'install basic CLI tools'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'coreutils'
      - 'iproute2'
      - 'grep'
      - 'curl'
      - 'wget'
      - 'which'
      - 'file'
      - 'tree'
      - 'man-db'
      - 'man-pages'

- name: 'find default editor'
  tags: 'user'
  ansible.builtin.set_fact:
    shell_basic_default_editor: >-
      {{
         user_config["editors"] |
         dict2items |
         selectattr("value.default", "defined") |
         selectattr("value.default") |
         map(attribute = "key") |
         first
      }}

- name: 'install profile drop-ins'
  tags: 'user'
  loop:
    - '01_01_default_editor'
  ansible.builtin.template:
    src: 'profile_dropins/{{ item }}.j2'
    dest: '{{ user_config["home_dir"] }}/{{ user_config["profile_dropins_dir"] }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644

- name: 'install drop-ins for shells'
  tags: 'user'
  loop: '{{ user_config["shells"] | dict2items }}'
  ansible.builtin.copy:
    src: 'shell_dropins/{{ item["key"] }}/'
    dest: '{{ user_config["home_dir"] }}/{{ item["value"]["config_dropins_dir"] }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
