---
- name: 'install the whole suite'
  hosts: 'all'
  tasks:
    - name: 'check mandatory clean_configs option'
      when: 'clean_configs is not defined or clean_configs not in ["no", "safe", "all"]'
      set_fact:
        clean_configs: 'safe'

    - name: 'apply basic roles'
      include_role:
        name: 'profile'

    - name: 'install shells'
      loop: '{{ user_config["shells"] | dict2items }}'
      include_role:
        name: 'shells/{{ role_item.key }}'
      vars:
        shell_config: '{{ role_item["value"] }}'
      loop_control:
        loop_var: 'role_item'

    - name: 'install editors'
      loop: '{{ user_config["editors"] | dict2items }}'
      include_role:
        name: 'editors/{{ role_item.key }}'
      vars:
        editor_config: '{{ user_config["editors"][role_item.key] }}'
      loop_control:
        loop_var: 'role_item'

    - name: 'install user`s desktop environment, if required'
      include_role:
        name: 'des/{{ user_config["gui"]["de"]["name"] }}'
      vars:
        de_config: '{{ user_config["gui"]["de"] }}'
      when: '"gui" in user_config and "de" in user_config["gui"]'

    - name: 'install toolchains required for user'
      include_role:
        name: 'tools/{{ toolchain_item.key }}'
      vars:
        toolchain_config: '{{ user_config["toolchains"][toolchain_item.key] }}'
      loop: '{{ user_config["toolchains"] | dict2items }}'
      loop_control:
        loop_var: 'toolchain_item'

    - name: 'install standalone applications'
      include_role:
        name: 'apps/{{ app_item.key }}'
      vars:
        app_config: '{{ user_config["apps"][app_item.key] }}'
      loop: '{{ user_config["apps"] | dict2items }}'
      loop_control:
        loop_var: 'app_item'
