---
- name: 'Install the whole suite'
  hosts: 'all'
  tasks:
    - name: 'Check mandatory clean_configs option'
      tags: 'user'
      when: 'clean_configs is not defined or clean_configs not in ["no", "safe", "all"]'
      ansible.builtin.set_fact:
        clean_configs: 'safe'

    - name: 'Fail if invalid user is requested'
      tags: 'user'
      when: 'user is defined and user not in users'
      ansible.builtin.fail:
        msg: >-
          User configuration for {{ user }} is requested
          explicitly, but no configuration for this user
          is found in inventory. Refusing to continue.

    - name: 'Limit users list to specific user'
      tags: 'user'
      when: 'user is defined and user in users'
      ansible.builtin.set_fact:
        user_items: >-
          {{
            users |
            dict2items |
            selectattr("key", "equalto", user)
          }}

    - name: 'Install Xorg'
      ansible.builtin.include_role:
        name: 'xorg'
      when: '"gui" in system'

    - name: 'Install DM'
      ansible.builtin.include_role:
        name: 'dms/{{ system["gui"]["dm"] }}'
      when: '"gui" in system and "dm" in system["gui"]'

    - name: 'Configure users'
      tags: 'user'
      loop: '{{ user_items | default(users | dict2items) }}'
      ansible.builtin.include_tasks:
        file: 'tasks/install_user.yml'
      vars:
        user_name: '{{ user_item.key }}'
        user_config: '{{ user_item.value }}'
      loop_control:
        loop_var: 'user_item'
