---
- name: 'install the whole suite'
  hosts: 'all'
  vars:
    vim_plugins:
      - 'nerdtree'
      - 'syntastic'
      - 'fugitive'
      - 'mru'
      - 'rust'
      - 'rustdoc'
      - 'commandt'
      - 'youcompleteme'
  roles:
    - 'bash'
    - 'vim'
    - 'viewnior'
