---
- name: 'install the whole suite'
  hosts: 'all'
  tasks:
    - name: 'apply basic roles'
      include_role:
        name: '{{ role_item }}'
      loop:
        - 'base/profile'
        - 'base/bash'
        - 'base/vim'
      loop_control:
        loop_var: 'role_item'

    - name: 'apply GUI roles'
      include_role:
        name: '{{ role_item }}'
      when: '"gui" in features'
      loop:
        - 'gui/gtk2'
        - 'gui/gtk3'
        - 'gui/alacritty'
        - 'gui/tilda'
        - 'gui/gmrun'
        - 'gui/viewnior'
        - 'gui/galculator'
      loop_control:
        loop_var: 'role_item'
