---
- name: 'install the whole suite'
  hosts: 'all'
  tasks:
    - name: 'check mandatory clean_configs option'
      tags: 'user'
      when: 'clean_configs is not defined or clean_configs not in ["no", "safe", "all"]'
      set_fact:
        clean_configs: 'safe'

    - name: 'fail if invalid user is requested'
      tags: 'user'
      when: 'user is defined and user not in users'
      fail:
        msg: >-
          User configuration for {{ user }} is requested
          explicitly, but no configuration for this user
          is found in inventory. Refusing to continue.

    - name: 'limit users list to specific user'
      tags: 'user'
      when: 'user is defined and user in users'
      set_fact:
       user_items: >-
        {{
          users |
          dict2items |
          selectattr("key", "equalto", user)
        }}

    - name: 'install Xorg'
      include_role:
        name: 'xorg'
      when: '"gui" in system'

    - name: 'install DM'
      include_role:
        name: 'dms/{{ system["gui"]["dm"] }}'
      when: '"gui" in system and "dm" in system["gui"]'

    - name: 'configure users'
      tags: 'user'
      loop: '{{ user_items | default (users | dict2items) }}'
      include_tasks:
        file: 'tasks/install_user.yml'
      vars:
        user_name: '{{ user_item.key }}'
        user_config: '{{ user_item.value }}'
      loop_control:
        loop_var: 'user_item'
