---
- name: 'install the whole suite'
  hosts: 'all'
  tasks:
    - name: 'fail if features are not set'
      fail:
        msg: 'Please define the desired feature flags in the "features" dictionary.'
      when: 'features is not defined'

    - name: 'apply GUI roles'
      include_role:
        name: '{{ role_item }}'
      when: '"gui" in features'
      loop:
        - 'xorg'
        - 'dms/lightdm'
      loop_control:
        loop_var: 'role_item'
