---
- name: 'install the whole suite'
  hosts: 'all'
  tasks:
    - name: 'fail if features are not set'
      fail:
        msg: 'Please define the desired feature flags in the "features" dictionary.'
      when: 'features is not defined'

    - name: 'apply basic roles'
      include_role:
        name: '{{ role_item }}'
      loop:
        - 'base/profile'
        - 'base/ssh'
      loop_control:
        loop_var: 'role_item'

    - name: 'install shells'
      loop: '{{ user_config["shells"] | dict2items }}'
      include_role:
        name: 'shells/{{ role_item.key }}'
      vars:
        shell_config: '{{ role_item["value"] }}'
      loop_control:
        loop_var: 'role_item'

    - name: 'install editors'
      loop: '{{ user_config["editors"] | dict2items }}'
      include_role:
        name: 'editors/{{ role_item.key }}'
      vars:
        editor_config: '{{ user_config["editors"][role_item.key] }}'
      loop_control:
        loop_var: 'role_item'

    - name: 'install user`s desktop environment, if required'
      include_role:
        name: 'des/{{ user_config["gui"]["de"] }}'
      when: '"gui" in user_config and "de" in user_config["gui"]'

    - name: 'install toolchains required for user'
      include_role:
        name: '{{ role_item }}'
      loop:
        - 'tools/shell-basic'
        - 'tools/shell-extras'
        - 'tools/devel-basic'
        - 'tools/devel-java'
        - 'tools/devel-rust'
        - 'tools/devel-go'
        - 'tools/devel-extras'
        - 'tools/media'
      loop_control:
        loop_var: 'role_item'

    # TODO: distribute this between toolchains!
    - name: 'install additional vim plugins'
      include_role:
        name: '{{ role_item }}'
      loop:
        - 'tools/vim-extras'
      loop_control:
        loop_var: 'role_item'

    - name: 'install standalone applications'
      include_role:
        name: 'apps/{{ role_item }}'
      loop:
        - 'vivaldi'
        - 'doublecmd'
        - 'sublime'
      loop_control:
        loop_var: 'role_item'
