---
- name: 'install the whole suite'
  hosts: 'all'
  tasks:
    - name: 'fail if features are not set'
      fail:
        msg: 'Please define the desired feature flags in the "features" dictionary.'
      when: 'features is not defined'

    - name: 'apply basic roles'
      include_role:
        name: '{{ role_item }}'
      loop:
        - 'base/profile'
        - 'base/ssh'
      loop_control:
        loop_var: 'role_item'

    - name: 'install shells'
      loop: '{{ user_config["shells"] | dict2items }}'
      include_role:
        name: 'shells/{{ role_item.key }}'
      vars:
        shell_config: '{{ role_item["value"] }}'
      loop_control:
        loop_var: 'role_item'

    - name: 'install editors'
      loop: '{{ user_config["editors"] | dict2items }}'
      include_role:
        name: 'editors/{{ role_item.key }}'
      vars:
        editor_config: '{{ user_config["editors"][role_item.key] }}'
      loop_control:
        loop_var: 'role_item'

    - name: 'install basic shell tools'
      include_role:
        name: 'tools/shell-basic'

    - name: 'install shell extras'
      include_role:
        name: 'tools/shell-extras'
      when: '"cli" in features and "extras" in features["cli"]'

    # XXX: installation of all toolchains will be merged together into a single loop
    # once we move a list of required toolchains into the user_config and replace all
    # existing dev roles with toolchains, deprecating the features.dev flag at all.
    #
    # Unless this, we have a little structural mess and apply many roles separately,
    # so these tools stand off other toolchains installation.
    - name: 'install toolchains required for user'
      include_role:
        name: '{{ role_item }}'
      loop:
        - 'tools/devel-basic'
        - 'tools/devel-java'
        - 'tools/devel-rust'
        - 'tools/devel-go'
        - 'tools/devel-extras'
      loop_control:
        loop_var: 'role_item'

    # TODO: distribute this between toolchains!
    - name: 'install additional vim plugins'
      include_role:
        name: '{{ role_item }}'
      loop:
        - 'tools/vim-extras'
      loop_control:
        loop_var: 'role_item'

    - name: 'install standalone GUI apps'
      include_role:
        name: 'apps/{{ role_item }}'
      loop:
        - 'vivaldi'
        - 'doublecmd'
        - 'sublime'
      loop_control:
        loop_var: 'role_item'

    - name: 'install multimedia toolchain'
      include_role:
        name: 'tools/media'

    - name: 'install user`s desktop environment, if required'
      include_role:
        name: 'des/{{ user_config["gui"]["de"] }}'
      when: '"gui" in user_config and "de" in user_config["gui"]'
