---
- name: 'install the whole suite'
  hosts: 'all'
  tasks:
    - name: 'fail if features are not set'
      fail:
        msg: 'Please define the desired feature flags in the "features" dictionary.'
      when: 'features is not defined'

    - name: 'install system tools'
      include_role:
        name: 'tools/{{ role_item }}'
      loop:
        - 'admin-system'
        - 'admin-network'
        - 'admin-tracing'
      loop_control:
        loop_var: 'role_item'

    - name: 'install Xorg'
      include_role:
        name: 'xorg'
      when: '"gui" in system'

    - name: 'install DM'
      include_role:
        name: 'dms/{{ system["gui"]["dm"] }}'
      when: '"gui" in system and "dm" in system["gui"]'
