---
- name: 'install vim'
  become: true
  become_user: 'root'
  package:
    name: 'vim'
    state: 'present'

- name: 'store vim dirs locations'
  tags: 'user'
  set_fact:
    autoload_dir: '{{ user_config["home_dir"] }}/.vim/autoload'
    bundle_dir: '{{ user_config["home_dir"] }}/{{ editor_config["plugins_dir"] }}'
    colors_dir: '{{ user_config["home_dir"] }}/.vim/colors'
    configs_dir: '{{ user_config["home_dir"] }}/{{ editor_config["config_dropins_dir"] }}'

- name: 'ensure .vim directory and its children exist'
  tags: 'user'
  loop:
    - '{{ user_config["home_dir"] }}/.vim'
    - '{{ autoload_dir }}'
    - '{{ bundle_dir }}'
    - '{{ colors_dir }}'
    - '{{ configs_dir }}'
  file:
    path: '{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: 'directory'
    mode: 0755

- name: 'install custom color schemes'
  tags: 'user'
  copy:
    src: 'vim/colors/'
    dest: '{{ colors_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644

- name: 'install basic .vimrc'
  tags: 'user'
  template:
    src: 'vimrc.j2'
    dest: '{{ user_config["home_dir"] }}/.vimrc'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644

- name: 'install pathogen'
  tags: 'user'
  get_url:
    url: '{{ vim_pathogen_url }}'
    dest: '{{ autoload_dir }}/pathogen.vim'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644

- with_items:
    - '{{ vim_basic_plugins | dict2items | map(attribute = "key") }}'
  tags: 'user'
  include_tasks:
    file: 'plugin.yml'
    apply:
      tags: 'user'
  loop_control:
    loop_var: 'plugin'
