---
- name: 'install vim'
  when: 'install_packages'
  become: true
  package:
    name: 'vim'
    state: 'present'

- name: 'store vim dirs locations'
  set_fact:
    autoload_dir: '{{ user_config["home_dir"] }}/.vim/autoload'
    bundle_dir: '{{ user_config["home_dir"] }}/.vim/bundle'
    colors_dir: '{{ user_config["home_dir"]}}/.vim/colors'
    configs_dir: '{{ user_config["home_dir"] }}/.vim/configs'

- name: 'ensure .vim directory and its children exist'
  loop:
    - '{{ user_config["home_dir"] }}/.vim'
    - '{{ autoload_dir }}'
    - '{{ bundle_dir }}'
    - '{{ colors_dir }}'
    - '{{ configs_dir }}'
  file:
    path: '{{ item }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755

- name: 'install custom color schemes'
  copy:
    src: 'vim/colors/'
    dest: '{{ colors_dir }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- name: 'install .vimrc'
  template:
    src: 'vimrc.j2'
    dest: '{{ user_config["home_dir"] }}/.vimrc'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- name: 'install pathogen'
  get_url:
    url: '{{ vim_pathogen_url }}'
    dest: '{{ autoload_dir }}/pathogen.vim'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- with_items:
    - '{{ vim_plugins }}'
  include_tasks: 'plugin.yml'
  vars:
    plugin_dir: '{{ bundle_dir }}/{{ plugin }}'
  loop_control:
    loop_var: 'plugin'
