---
- name: 'Check that role supports target OS'
  when: 'ansible_os_family not in ["Archlinux"]'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      target OS family is: {{ ansible_os_family }}.

- name: 'Install Xorg server, utilities and fonts'
  become: true
  ansible.builtin.package:
    name:
      - 'xorg-server'
      - 'xorg-apps'
      - 'ttf-dejavu'
      - 'ttf-opensans'
    state: 'present'

# XXX: /usr/share/icons and /etc/X11 are owned by the package manager
# and must already be present after xorg-xserver and xorg-apps installation.
#
# Wallpapers directory is custom, so we create it.
- name: 'Ensure wallpapers directory exists'
  become: true
  ansible.builtin.file:
    path: '/usr/local/share/wallpapers'
    owner: 'root'
    group: 'root'
    state: 'directory'
    mode: '0755'

- name: 'Install common Xorg configuration'
  become: true
  loop:
    - '00_disable_screensaver.conf'
    - '10_keyboard.conf'
  ansible.builtin.copy:
    src: 'xorg.conf/{{ item }}'
    dest: '/etc/X11/xorg.conf.d/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Install laptop Xorg configuration'
  when: 'system["laptop"]'
  become: true
  loop:
    - '20_touchpad.conf'
  ansible.builtin.copy:
    src: 'xorg.conf/{{ item }}'
    dest: '/etc/X11/xorg.conf.d/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Install global Xresources'
  become: true
  ansible.builtin.template:
    src: 'Xresources.j2'
    dest: '/etc/X11/Xresources'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Install icons'
  become: true
  ansible.builtin.copy:
    src: 'icons/'
    dest: '/usr/share/icons'
    owner: 'root'
    group: 'root'
    mode: '0644'
    local_follow: false

- name: 'Install wallpapers'
  become: true
  ansible.builtin.copy:
    src: 'wallpapers/'
    dest: '/usr/local/share/wallpapers'
    owner: 'root'
    group: 'root'
    mode: '0644'
