---
- name: 'install Xorg server, utilities and fonts'
  become: true
  package:
    name:
      - 'xorg-server'
      - 'xorg-apps'
      - 'ttf-dejavu'
      - 'ttf-opensans'
    state: 'present'

# XXX: /usr/share/icons and /etc/X11 are owned by the package manager
# and must already be present after xorg-xserver and xorg-apps installation.
#
# Wallpapers directory is custom, so we create it.
- name: 'ensure wallpapers directory exists'
  become: true
  file:
    path: '/usr/local/share/wallpapers'
    owner: 'root'
    group: 'root'
    state: 'directory'
    mode: 0755

- name: 'install common Xorg configuration'
  become: true
  loop:
    - '00_disable_screensaver.conf'
    - '10_keyboard.conf'
  copy:
    src: 'xorg.conf/{{ item }}'
    dest: '/etc/X11/xorg.conf.d/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: 'install laptop Xorg configuration'
  become: true
  when: 'system["laptop"]'
  loop:
    - '20_touchpad.conf'
  copy:
    src: 'xorg.conf/{{ item }}'
    dest: '/etc/X11/xorg.conf.d/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: 'install global Xresources'
  become: true
  template:
    src: 'Xresources.j2'
    dest: '/etc/X11/Xresources'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: 'install icons'
  become: true
  copy:
    src: 'icons/'
    dest: '/usr/share/icons'
    owner: 'root'
    group: 'root'
    mode: 0644
    local_follow: false

- name: 'install wallpapers'
  become: true
  copy:
    src: 'wallpapers/'
    dest: '/usr/local/share/wallpapers'
    owner: 'root'
    group: 'root'
    mode: 0644
