---
tools_devel_basic_editor_plugins:
  vim:
    fugitive:
      repo: 'https://github.com/tpope/vim-fugitive'
      requires_config: true

# Freestanding configs which do not belong to any particular plugin.
tools_devel_basic_editor_configs:
  vim:
    - 'xml_format_hotkey.vim'
