---
- name: 'Install Java packages'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'jdk-openjdk'
      - 'openjdk-doc'
      - 'openjdk-src'

      - 'jdk17-openjdk'
      - 'openjdk17-doc'
      - 'openjdk17-src'

      - 'jdk11-openjdk'
      - 'openjdk11-doc'
      - 'openjdk11-src'

      - 'ant'
      - 'maven'
      - 'gradle'
      - 'bazel'

      - 'netbeans'
      - 'visualvm'

- name: 'Install templated shell drop-ins'
  tags: 'user'
  vars:
    java_dropin_templates:
      - '13_01_java_aliases'
  loop: '{{ user_config["shells"] | dict2items | product(java_dropin_templates) }}'
  ansible.builtin.template:
    src: 'shell_dropins/{{ item[0]["key"] }}/{{ item[1] }}.j2'
    dest: '{{ user_config["home_dir"] }}/{{ item[0]["value"]["config_dropins_dir"] }}/{{ item[1] }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
