---
- name: 'install Java packages'
  when: 'install_packages'
  become: true
  package:
    state: 'present'
    name:
      - 'jdk-openjdk'
      - 'openjdk-doc'
      - 'openjdk-src'

      - 'jdk17-openjdk'
      - 'openjdk17-doc'
      - 'openjdk17-src'

      - 'jdk11-openjdk'
      - 'openjdk11-doc'
      - 'openjdk11-src'

      - 'ant'
      - 'maven'
      - 'gradle'
      - 'bazel'

      - 'netbeans'
      - 'visualvm'

- name: 'install templated shell drop-ins'
  vars:
    java_dropin_templates:
      - '13_01_java_aliases'
  loop: '{{ user_config["shells"] | dict2items | product(java_dropin_templates) }}'
  template:
    src: 'shell_dropins/{{ item[0]["key"] }}/{{ item[1] }}.j2'
    dest: '{{ user_config["home_dir"] }}/{{ item[0]["value"]["dropins_dir"] }}/{{ item[1] }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
