---
- name: 'install doublecmd package'
  become: true
  package:
    name: 'doublecmd-gtk2'
    state: 'present'

- name: 'delete doublecmd configs if required'
  tags: 'user'
  when: 'clean_configs == "all"'
  file:
    path: '{{ user_config["home_dir"] }}/.config/doublecmd'
    state: 'absent'

- name: 'check for doublecmd config directory'
  tags: 'user'
  stat:
    path: '{{ user_config["home_dir"] }}/.config/doublecmd'
  register: 'dconfig_result'

- name: 'install doublecmd configs'
  tags: 'user'
  when: 'not dconfig_result.stat.exists'
  block:
    - name: 'create doublecmd configs directory'
      file:
        path: '{{ user_config["home_dir"] }}/.config/doublecmd'
        owner: '{{ user_name }}'
        group: '{{ user_name }}'
        state: 'directory'
        mode: 0755

    - name: 'install doublecmd.xml'
      template:
        src: 'doublecmd.xml.j2'
        dest: '{{ user_config["home_dir"] }}/.config/doublecmd/doublecmd.xml'
        owner: '{{ user_name }}'
        group: '{{ user_name }}'
        mode: 0644

    - name: 'install ignorelist.txt'
      copy:
        src: 'ignorelist.txt'
        dest: '{{ user_config["home_dir"] }}/.config/doublecmd/ignorelist.txt'
        owner: '{{ user_name }}'
        group: '{{ user_name }}'
        mode: 0644
