---
- name: 'install alacritty'
  when: 'install_packages'
  become: true
  package:
    name: 'alacritty'
    state: 'present'

- name: 'ensure alacritty config directory exists'
  file:
    path: '{{ user_config["home_dir"] }}/.config/alacritty'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755

- name: 'install alacritty config'
  copy:
    src: 'alacritty.toml'
    dest: '{{ user_config["home_dir"] }}/.config/alacritty/alacritty.toml'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
