---
- name: 'Fail if role does not support target OS'
  when: 'ansible_os_family not in ["Archlinux"]'
  tags: 'user'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      target OS family is: {{ ansible_os_family }}.

- name: 'Install web development packages'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'chromium'
      - 'firefox'
