---
- name: 'get home dir of {{ user }}'
  getent:
    database: 'passwd'
    key: '{{ user }}'
    split: ':'

- name: 'store home dir of {{ user }}'
  set_fact:
    home_dir: '{{ getent_passwd[user][4] }}'

- name: 'ensure X icons directory exists'
  file:
    path: '{{ home_dir }}/.local/share/icons'
    owner: '{{ user }}'
    group: '{{ user }}'
    state: 'directory'
    mode: 0755

- name: 'install icons'
  copy:
    src: 'icons/'
    dest: '{{ home_dir }}/.local/share/icons'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644
    local_follow: false

- name: 'install .Xresources'
  template:
    src: 'Xresources.j2'
    dest: '{{ home_dir }}/.Xresources'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644
