---
- name: 'install system tracing and debugging tools'
  when: 'install_packages'
  become: true
  package:
    state: 'present'
    name:
      - 'perf'
      - 'trace-cmd'
      - 'strace'
      - 'ltrace'
