---
- name: 'install system tracing and debugging tools'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'perf'
      - 'trace-cmd'
      - 'strace'
      - 'ltrace'
