---
- name: 'Install vivaldi packages'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    name:
      - 'vivaldi'
      - 'vivaldi-ffmpeg-codecs'
    state: 'present'

- name: 'Ensure vivaldi downloads directory exists'
  tags: 'user'
  ansible.builtin.file:
    path: '{{ user_config["home_dir"] }}/{{ user_config["downloads_dir"] }}/vivaldi'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: 'directory'
    mode: 0755

- name: 'Delete vivaldi configs if required'
  tags: 'user'
  ansible.builtin.file:
    path: '{{ user_config["home_dir"] }}/.config/vivaldi'
    state: 'absent'
  when: 'clean_configs == "all"'

- name: 'Check for vivaldi config directory'
  tags: 'user'
  ansible.builtin.stat:
    path: '{{ user_config["home_dir"] }}/.config/vivaldi'
  register: 'vconfig_result'

- name: 'Install vivaldi config'
  tags: 'user'
  when: 'not vconfig_result.stat.exists'
  block:
    - name: 'Create vivaldi config directory'
      ansible.builtin.file:
        path: '{{ user_config["home_dir"] }}/.config/vivaldi/Default'
        owner: '{{ user_name }}'
        group: '{{ user_name }}'
        state: 'directory'
        mode: 0755

    - name: 'Install vivaldi preferences'
      ansible.builtin.template:
        src: 'Preferences.j2'
        dest: '{{ user_config["home_dir"] }}/.config/vivaldi/Default/Preferences'
        owner: '{{ user_name }}'
        group: '{{ user_name }}'
        mode: 0644
