---
- name: 'install network administration tools'
  when: 'install_packages'
  become: true
  package:
    state: 'present'
    name:
      - 'which'
      - 'socat'
      - 'man-db'
      - 'man-pages'
      - 'pciutils'
      - 'usbutils'
      - 'smartmontools'
      - 'lm_sensors'
      - 'upower'
      - 'lshw'
      - 'hwloc'
