---
- name: 'install qaztom packages'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    name:
      - 'xdg-utils'
      - 'openbox'
      - 'xcompmgr'
      - 'feh'
      - 'alsa-utils'
      - 'pulseaudio'
      - 'gtk2'
      - 'gtk3'
      - 'gnome-themes-extra'
      - 'tilda'
      - 'alacritty'
      - 'gmrun'
      - 'xfce4-panel'
      - 'xfce4-xkb-plugin'
      - 'xfce4-battery-plugin'
      - 'xfce4-pulseaudio-plugin'
      - 'xfce4-screenshooter'
      - 'pavucontrol'
      - 'galculator'
      - 'viewnior'
      - 'guvcview'
      - 'zathura'
      - 'zathura-djvu'
      - 'zathura-pdf-poppler'
      - 'zathura-ps'
      - 'audacious'
      - 'vlc'
    state: 'present'

- name: 'configure desktop environment apps'
  tags: 'user'
  loop: '{{ openbox_qaztom_apps | dict2items | map(attribute = "key") }}'
  ansible.builtin.include_tasks:
    file: 'configure_app.yml'
    apply:
      tags: 'user'
  vars:
    qaztom_app_name: '{{ de_app_item }}'
  loop_control:
    loop_var: 'de_app_item'

- name: 'install profile drop-ins'
  tags: 'user'
  loop:
    - '20_01_hidpi_vars'
  ansible.builtin.template:
    src: 'profile_dropins/{{ item }}.j2'
    dest: '{{ user_config["home_dir"] }}/{{ user_config["profile_dropins_dir"] }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
