---
user: "{{ ansible_user_id }}"

# By default, install only plugins which are unlikely to cause any pain.
vim_plugins:
  - nerdtree
  - fugitive
  - mru

rustup_toolchain: nightly-x86_64-unknown-linux-gnu
