---
- name: 'Check that role supports target OS'
  when: 'ansible_os_family not in ["Archlinux"]'
  tags: 'user'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      target OS family is: {{ ansible_os_family }}.

- name: 'Install basic development tools'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'binutils'

      # Basic C toolchain. it is in base, as it is used for numerous things,
      # not only for C development.
      - 'm4'
      - 'make'
      - 'autoconf'
      - 'automake'
      - 'cmake'
      - 'pkgconf'
      - 'gcc'

      # Versioning and patching tools.
      - 'git'
      - 'diffutils'
      - 'patch'

      # These libs are used for XML processing.
      #
      # Though they are usually installed as dependencies, we install them
      # explicitly to know that we have xmllint and xsltproc tools in the system.
      # These are needed for poor man's XML autoformatting hotkeys in editors.
      - 'libxml2'
      - 'libxslt'

- name: 'Install drop-ins for shells'
  tags: 'user'
  loop: '{{ user_config.shells | dict2items }}'
  ansible.builtin.copy:
    src: 'shell_dropins/{{ item.key }}/'
    dest: '{{ user_config.home_dir }}/{{ item.value.config_dropins_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'

- name: 'Install templated profile drop-ins'
  tags: 'user'
  loop:
    - '10_01_dev_base_xmllint'
  ansible.builtin.template:
    src: 'profile_dropins/{{ item }}.j2'
    dest: '{{ user_config.home_dir }}/{{ user_config.profile_dropins_dir }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'

- name: 'Install drop-ins for editors'
  tags: 'user'
  loop: '{{ user_config.editors | dict2items | map(attribute="key") }}'
  loop_control:
    loop_var: 'editor_item'
  vars:
    editor: '{{ editor_item }}'
  ansible.builtin.include_tasks:
    file: 'editor_config.yml'
    apply:
      tags: 'user'
