---
- name: 'Check that role supports target OS'
  when: 'ansible_os_family not in ["Archlinux"]'
  tags: 'user'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      target OS family is: {{ ansible_os_family }}.

- name: 'Install Java development packages'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'jdk-openjdk'
      - 'openjdk-doc'
      - 'openjdk-src'

      - 'jdk17-openjdk'
      - 'openjdk17-doc'
      - 'openjdk17-src'

      - 'jdk11-openjdk'
      - 'openjdk11-doc'
      - 'openjdk11-src'

      - 'ant'
      - 'maven'
      - 'gradle'
      - 'bazel'

- name: 'Install GUI Java development tools'
  when: '"gui" in user_config'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'netbeans'
      - 'visualvm'

- name: 'Install templated shell drop-ins'
  tags: 'user'
  loop: '{{ user_config.shells | dict2items | product(java_dropin_templates) }}'
  vars:
    java_dropin_templates:
      - '13_01_java_aliases'
  ansible.builtin.template:
    src: 'shell_dropins/{{ item.0.key }}/{{ item.1 }}.j2'
    dest: '{{ user_config.home_dir }}/{{ item.0.value.config_dropins_dir }}/{{ item.1 }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'
