---
- name: 'add sublime repo'
  become: true
  blockinfile:
    dest: '/etc/pacman.conf'
    prepend_newline: true
    append_newline: true
    block: |
      [sublime-text]
      Server = https://download.sublimetext.com/arch/stable/x86_64

- name: 'import sublime repo key'
  become: true
  community.general.pacman_key:
    id: '{{ sublime_gpg_publickey }}'
    data: '{{ lookup("file", "sublimehq-publickey.gpg") }}'
    state: 'present'

- name: 'install sublime-text package'
  become: true
  pacman:
    name: 'sublime-text'
    state: 'present'
    update_cache: true

- name: 'check for sublime user config directory'
  tags: 'user'
  file:
    path: '{{ sublime_user_config_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: 'directory'
    mode: 0755

- name: 'install sublime configs'
  tags: 'user'
  loop:
    - 'NetBeans.tmTheme'
    - 'Preferences.sublime-settings'
  copy:
    src: '{{ item }}'
    dest: '{{ sublime_user_config_dir }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
