---
- name: 'Install network administration tools'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'bind-tools'
      - 'traceroute'
      - 'gnu-netcat'
      - 'mtr'
      - 'tcpdump'
      - 'nmap'
      - 'curl'

      # TODO: this is user-preference and distro-specific stuff.
      # Introduce feature flags to define what is used to manage
      # network connections.
      - 'dhcpcd'
      - 'netctl'
      - 'dialog'
      - 'wpa_supplicant'
      - 'ifplugd'
      - 'openresolv'

- name: 'Install GUI network administration tools'
  when: '"gui" in user_config'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'wireshark-qt'
