---
- name: 'install xorg'
  package:
    name: 'xorg-server'
    state: 'present'

- name: 'install xorg utilities'
  package:
    name: 'xorg-apps'
    state: 'present'

- name: 'install fonts'
  loop:
    - 'ttf-dejavu'
    - 'ttf-opensans'
  package:
    name: '{{ item }}'
    state: 'present'

- name: 'ensure xorg config directory exists'
  file:
    path: '/etc/X11/xorg.conf.d'
    owner: 'root'
    group: 'root'
    state: 'directory'
    mode: 0755

- name: 'install common xorg configuration'
  loop:
    - '00_disable_screensaver.conf'
    - '10_keyboard.conf'
  copy:
    src: '{{ item }}'
    dest: '/etc/X11/xorg.conf.d/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: 'install laptop xorg configuration'
  when: 'system["laptop"]'
  loop:
    - '20_touchpad.conf'
  copy:
    src: '{{ item }}'
    dest: '/etc/X11/xorg.conf.d/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: 0644
