---
- name: 'find default toolchains'
  set_fact:
    rustup_default_toolchains: >-
      {{
         toolchain_config["rustup_toolchains"] |
         selectattr("default", "defined") |
         selectattr("default") |
         map(attribute = "name")
      }}

- name: 'check that exactly one toolchain is default'
  when: 'rustup_default_toolchains | length == 0 or rustup_default_toolchains | length > 1'
  fail:
    msg: 'Configuration error: exactly one Rust toolchain must be default!'

- name: 'install rustup package'
  when: 'install_packages'
  become: true
  package:
    state: 'present'
    name:
      - 'rustup'

- name: 'install rust toolchains'
  loop: '{{ toolchain_config["rustup_toolchains"] | map(attribute = "name") }}'
  shell:
    argv:
      - 'rustup'
      - 'toolchain'
      - 'install'
      - '{{ item }}'

- name: 'set default rust toolchain'
  shell:
    argv:
      - 'rustup'
      - 'default'
      - '{{ rustup_default_toolchains | first }}'

- name: 'add mandatory rust components'
  loop:
    - 'rust-src'
    - 'rust-docs'
    - 'rust-analyzer'
  shell:
    argv:
      - 'rustup'
      - 'component'
      - 'add'
      - '{{ item }}'

- name: 'add user-requsted cargo components'
  loop: '{{ toolchain_config["cargo_plugins"] }}'
  when: '"cargo_plugins" in toolchain_config'
  shell:
    argv:
      - 'cargo'
      - 'install'
      - '{{ item }}'
