---
- name: 'install viewnior'
  when: 'install_packages'
  become: true
  package:
    name: 'viewnior'
    state: 'present'

- name: 'ensure viewnior config directory exists'
  file:
    path: '{{ user_config["home_dir"] }}/.config/viewnior'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755

- name: 'install viewnior config'
  copy:
    src: 'viewnior.conf'
    dest: '{{ user_config["home_dir"] }}/.config/viewnior/viewnior.conf'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
