---
tools_shell_extras_editor_plugins:
  vim:
    fzf:
      repo: 'https://github.com/junegunn/fzf'
      requires_config: false
    fzf_vim:
      repo: 'https://github.com/junegunn/fzf.vim'
      requires_config: true

tools_shell_extras_base_packages:
  - 'mlocate'
  - 'moreutils'
  - 'ripgrep'
  - 'bat'
  - 'jq'
  - 'wget'
  - 'lynx'

tools_shell_extras_packages:
  Archlinux: >-
    {{
      tools_shell_extras_base_packages +

      ['fd', 'fzf']
    }}

  # XXX: fzf is not yet available as ordinary package in EPEL8, so it is
  # installed as plain statically-linked binary.
  RedHat: >-
    {{
      tools_shell_extras_base_packages +

      ['fd-find']
    }}

  PureOS: >-
    {{
      tools_shell_extras_base_packages +

      ['fd-find', 'fzf']
    }}

# The parameters below apply only to fallback static binary installation, so
# they are private to the role and are not considered parts of toolchain
# config, though it could be a good idea to specify version in inventories.

# Unfortunately, different tools use different names for same architectures, so
# we need to maintain the mapping between target host's arch and platform names
# in different builds.
tools_shell_extras_platforms:
  x86_64:
    fzf: 'amd64'

tools_shell_extras_fzf_version: '0.53.0'
tools_shell_extras_fzf_repo: 'https://github.com/junegunn/fzf'
tools_shell_extras_fzf_release: "\
  {{ tools_shell_extras_fzf_repo }}/releases/download/\
  {{ tools_shell_extras_fzf_version }}/fzf-{{ tools_shell_extras_fzf_version }}\
  -linux_{{ tools_shell_extras_platforms[ansible_architecture].fzf }}.tar.gz"
tools_shell_extras_fzf_sources: "\
  {{ tools_shell_extras_fzf_repo }}/archive/refs/tags/\
  {{ tools_shell_extras_fzf_version }}.tar.gz"
