---
tools_shell_extras_editor_plugins:
  vim:
    fzf:
      repo: 'https://github.com/junegunn/fzf'
      requires_config: false
    fzf_vim:
      repo: 'https://github.com/junegunn/fzf.vim'
      requires_config: true

tools_shell_extras_packages:
  Archlinux:
    - 'mlocate'
    - 'moreutils'
    - 'ripgrep'
    - 'fd'
    - 'fzf'
    - 'bat'
    - 'jq'
    - 'yq'
    - 'wget'
    - 'lynx'

  # XXX: fd, fzf and bat are not yet available as ordinary packages, so they
  # are installed as plain statically-linked binaries.
  #
  # yq and lynx are not available as packages, but there is no real need for
  # them on servers, so they are simply discarded for the RedHat family.
  # Probably, these tools (along with jq?) deserve to be moved out of this
  # toolchain?
  RedHat:
    - 'mlocate'
    - 'moreutils'
    - 'ripgrep'
    - 'jq'
    - 'wget'

# These parameters apply only to fallback static binary installation, so they
# are private to the role and are not considered parts of toolchain config,
# though it could be a good idea to specify version in inventories.
tools_shell_extras_fzf_version: '0.46.0'
tools_shell_extras_fzf_repo: 'https://github.com/junegunn/fzf'
tools_shell_extras_fzf_release: "\
  {{ tools_shell_extras_fzf_repo }}/releases/download/\
  {{ tools_shell_extras_fzf_version }}/fzf-{{ tools_shell_extras_fzf_version }}\
  -linux_amd64.tar.gz"
tools_shell_extras_fzf_sources: "\
  {{ tools_shell_extras_fzf_repo }}/archive/refs/tags/\
  {{ tools_shell_extras_fzf_version }}.tar.gz"

tools_shell_extras_fd_version: '9.0.0'
tools_shell_extras_fd_releases: 'https://github.com/sharkdp/fd/releases/download'
tools_shell_extras_fd_release: "\
  {{ tools_shell_extras_fd_releases }}/v{{ tools_shell_extras_fd_version }}/\
  fd-v{{ tools_shell_extras_fd_version }}-i686-unknown-linux-musl.tar.gz"

tools_shell_extras_bat_version: '0.24.0'
tools_shell_extras_bat_releases: 'https://github.com/sharkdp/bat/releases/download'
tools_shell_extras_bat_release: "\
  {{ tools_shell_extras_bat_releases }}/v{{ tools_shell_extras_bat_version }}/\
  bat-v{{ tools_shell_extras_bat_version }}-x86_64-unknown-linux-musl.tar.gz"
