---
- name: 'store editor-related settings'
  set_fact:
    plugins_dir: '{{ user_config["home_dir"] }}/{{ user_config["editors"][editor]["plugins_dir"] }}'
    configs_dir: '{{ user_config["home_dir"] }}/{{ user_config["editors"][editor]["config_dropins_dir"] }}'
    role_editor_settings: '{{ shell_extras_editor_plugins[editor] }}'

- name: 'install plugins for {{ editor }}'
  loop: '{{ role_editor_settings | dict2items | map(attribute = "key") }}'
  vars:
    plugin: '{{ item }}'
  include_tasks:
    file: '{{ editor }}_plugin.yml'
    apply:
      tags: 'user'
