---
- name: 'install extra CLI tools'
  when: 'install_packages'
  become: true
  package:
    state: 'present'
    name:
      - 'moreutils'
      - 'ripgrep'
      - 'fd'
      - 'fzf'
      - 'bat'
      - 'jq'
      - 'yq'
      - 'lynx'

- name: 'install profile drop-ins'
  copy:
    src: 'profile_dropins/'
    dest: '{{ user_config["home_dir"] }}/{{ user_config["profile_dropins_dir"] }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- name: 'install drop-ins for shells'
  loop: '{{ user_config["shells"] | dict2items }}'
  copy:
    src: 'shell_dropins/{{ item["key"] }}/'
    dest: '{{ user_config["home_dir"] }}/{{ item["value"]["config_dropins_dir"] }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- name: 'install drop-ins for editors'
  loop: '{{ user_config["editors"] | dict2items | map(attribute = "key") }}'
  loop_control:
    loop_var: 'editor_item'
  vars:
    editor: '{{ editor_item }}'
  include_tasks:
    file: 'editor_config.yml'
