---
- name: 'find plugin config for {{ plugin }}'
  set_fact:
    plugin_config: '{{ role_editor_settings[plugin] }}'
    plugin_dir: '{{ plugins_dir }}/{{ plugin }}'

- name: 'download {{ plugin }} plugin'
  git:
    repo: '{{ plugin_config.repo }}'
    dest: '{{ plugin_dir }}'
    depth: 1
    force: true

- name: 'install {{ plugin }} plugin config'
  when: 'plugin_config.requires_config'
  copy:
    src: 'editor_configs/vim/{{ plugin }}.vim'
    dest: '{{ configs_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644
