---
vim_pathogen_url: https://tpo.pe/pathogen.vim

vim_basic_plugins:
  youarehere:
    repo: https://github.com/bignimbus/you-are-here.vim.git
    requires_config: true

  nerdtree:
    repo: https://github.com/scrooloose/nerdtree
    requires_config: true
