---
- name: 'install openbox'
  when: 'install_packages'
  become: true
  package:
    name: 'openbox'
    state: 'present'

- name: 'ensure openbox config directory exists'
  file:
    path: '{{ user_config["home_dir"] }}/.config/openbox'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755

- name: 'install {{ item }} openbox config'
  loop:
    - 'autostart'
    - 'rc.xml'
    - 'menu.xml'
  template:
    src: '{{ item }}.j2'
    dest: '{{ user_config["home_dir"] }}/.config/openbox/{{ item }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
  notify: 'reconfigure openbox'
