---
- name: 'install gmrun'
  when: 'install_packages'
  become: true
  package:
    name: 'gmrun'
    state: 'present'

- name: 'install gmrun config'
  copy:
    src: 'gmrunrc'
    dest: '{{ user_config["home_dir"] }}/.gmrunrc'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
