---
- name: 'Check that role supports target OS'
  when: 'ansible_os_family not in ["Archlinux", "RedHat"]'
  tags: 'user'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      target OS family is: {{ ansible_os_family }}.

- name: 'Install system tracing and debugging tools'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'perf'
      - 'trace-cmd'
      - 'strace'
      - 'ltrace'
