---
- name: 'Fail if role does not support target OS'
  when: 'ansible_os_family not in ["Archlinux"]'
  tags: 'user'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      target OS family is: {{ ansible_os_family }}.

- name: 'Install qaztom packages'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    name:
      - 'xdg-utils'
      - 'openbox'
      - 'xcompmgr'
      - 'feh'
      - 'alsa-utils'
      - 'pulseaudio'
      - 'gtk2'
      - 'gtk3'
      - 'gnome-themes-extra'
      - 'tilda'
      - 'alacritty'
      - 'gmrun'
      - 'xfce4-panel'
      - 'xfce4-xkb-plugin'
      - 'xfce4-battery-plugin'
      - 'xfce4-pulseaudio-plugin'
      - 'xfce4-screenshooter'
      - 'pavucontrol'
      - 'galculator'
      - 'viewnior'
      - 'guvcview'
      - 'zathura'
      - 'zathura-djvu'
      - 'zathura-pdf-poppler'
      - 'zathura-ps'
      - 'audacious'
      - 'vlc'
      - 'xournalpp'
    state: 'present'

- name: 'Configure desktop environment apps'
  tags: 'user'
  loop: '{{ des_openbox_qaztom_apps | dict2items | map(attribute="key") }}'
  loop_control:
    loop_var: 'de_app_item'
  vars:
    qaztom_app_name: '{{ de_app_item }}'
  ansible.builtin.include_tasks:
    file: 'configure_app.yml'
    apply:
      tags: 'user'

- name: 'Install profile drop-ins'
  tags: 'user'
  loop:
    - '20_01_hidpi_vars'
  ansible.builtin.template:
    src: 'profile_dropins/{{ item }}.j2'
    dest: '{{ user_config.home_dir }}/{{ user_config.profile_dropins_dir }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'
