---
- name: 'install galculator'
  when: 'install_packages'
  become: true
  package:
    name: 'galculator'
    state: 'present'

- name: 'ensure galculator config directory exists'
  file:
    path: '{{ user_config["home_dir"] }}/.config/galculator'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755

- name: 'install galculator config'
  copy:
    src: 'galculator.conf'
    dest: '{{ user_config["home_dir"] }}/.config/galculator/galculator.conf'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
