---
tools_admin_system_basic_packages:
  - 'htop'
  - 'socat'
  - 'pciutils'
  - 'usbutils'
  - 'smartmontools'
  - 'upower'
  - 'powertop'
  - 'lshw'
  - 'hwloc'
  - 'iotop'
  - 'firejail'

tools_admin_system_packages:
  Archlinux: >-
    {{
      tools_admin_system_basic_packages +

      ['lm_sensors'] +

      ['acpi', 'usb_modeswitch']
    }}

  RedHat: >-
    {{
      tools_admin_system_basic_packages +

      ['lm_sensors']
    }}

  PureOS: >-
    {{
      tools_admin_system_basic_packages +

      ['lm-sensors']
    }}
