---
- name: 'install ssh'
  when: 'install_packages'
  become: true
  package:
    name: 'openssh'
    state: 'present'

- name: 'ensure .ssh and config.d directories exist'
  loop:
    - '.ssh'
    - '.ssh/config.d'
  file:
    path: '{{ user_config["home_dir"] }}/{{ item }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0700

- name: 'install ssh config'
  template:
    src: 'config.j2'
    dest: '{{ user_config["home_dir"] }}/.ssh/config'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

# XXX: do not bother with creating custom units for non-Arch systems, as currently
# the agent is required only for client machines, which are Arch desktops, and Arch
# has a default agent unit shipepd with openssh package (which is not the case for,
# say, CentOS / Almalinux).
- name: 'enable ssh agent'
  when: 'ansible_os_family == "Archlinux" and ssh["use_agent"]'
  systemd_service:
    name: 'ssh-agent'
    scope: 'user'
    state: 'started'
    enabled: true
