---
de_config:

  # There is no option 'stick to bottom, stretch to full width'; instead xfce stores
  # raw coordinates which depend on resolution (and, probably, DPI?) and are not that
  # easy to calculate in the playbook, so we just parameterize that.
  #
  # There probably will be a need for a minor manual reconfiguration after the initial
  # installation (reconfigure panel, store coordinates and commit them), but that's
  # better than just configuring whole panel manually.
  #
  # The role defaults are suitable for 1920x1080 resolution, which is nowadays usual
  # for ordinary laptops.
  xfce_panel:
      x: 960
      y: 1066

  # Uncomment to set the wallpaper under Tilda.
  # wallpaper: /path/to/file
