---
- name: 'Install vbox backend for vagrant'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'virtualbox-host-modules-arch'
      - 'virtualbox-guest-iso'
