---
toolchain_config:

# Uncomment to auto-install a backend for vagrant.
#
#  vagrant_backend: 'virtualbox'

devel_extra_editor_plugins:
  vim:
    youcompleteme:
      repo: https://github.com/Valloric/YouCompleteMe
      requires_build: true
      requires_config: true
