---
- name: 'find plugin config for {{ plugin }}'
  set_fact:
    plugin_config: '{{ vim_extra_plugins[plugin] }}'
    plugin_dir: '{{ bundle_dir }}/{{ plugin }}'

- name: 'download {{ plugin }} plugin'
  git:
    repo: '{{ plugin_config.repo }}'
    dest: '{{ plugin_dir }}'
    depth: 1
    force: true

- name: 'install {{ plugin }} plugin config'
  when: 'plugin_config.requires_config'
  copy:
    src: 'vim/configs/{{ plugin }}.vim'
    dest: '{{ configs_dir }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- include_tasks: 'plugins/{{ plugin }}_build.yml'
  when: 'plugin_config.requires_build'
