---
- name: 'Install ssh'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    name: 'openssh'
    state: 'present'

- name: 'Ensure .ssh and config.d directories exist'
  tags: 'user'
  loop:
    - '.ssh'
    - '.ssh/config.d'
  ansible.builtin.file:
    path: '{{ user_config.home_dir }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: 'directory'
    mode: '0700'

- name: 'Install ssh config'
  tags: 'user'
  ansible.builtin.template:
    src: 'config.j2'
    dest: '{{ user_config.home_dir }}/.ssh/config'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'

- name: 'Install templated profile drop-ins'
  tags: 'user'
  loop:
    - '03_01_ssh_agent_socket'
  ansible.builtin.template:
    src: 'profile_dropins/{{ item }}.j2'
    dest: '{{ user_config.home_dir }}/{{ user_config.profile_dropins_dir }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'

# XXX: do not bother with creating custom units for non-Arch systems, as currently
# the agent is required only for client machines, which are Arch desktops, and Arch
# has a default agent unit shipepd with openssh package (which is not the case for,
# say, CentOS / Almalinux).
- name: 'Enable ssh agent'
  tags: 'user'
  when: 'ansible_os_family == "Archlinux" and app_config.use_agent'
  ansible.builtin.systemd_service:
    name: 'ssh-agent'
    scope: 'user'
    state: 'started'
    enabled: true
