---
- name: 'Store editor-related settings'
  ansible.builtin.set_fact:
    plugins_dir: '{{ user_config["home_dir"] }}/{{ user_config["editors"][editor]["plugins_dir"] }}'
    configs_dir: '{{ user_config["home_dir"] }}/{{ user_config["editors"][editor]["config_dropins_dir"] }}'
    role_editor_plugins: '{{ tools_devel_basic_editor_plugins[editor] }}'
    role_editor_configs: '{{ tools_devel_basic_editor_configs[editor] }}'

- name: 'Install plugins for {{ editor }}'
  loop: '{{ role_editor_plugins | dict2items | map(attribute="key") }}'
  vars:
    plugin: '{{ item }}'
  ansible.builtin.include_tasks:
    file: '{{ editor }}_plugin.yml'
    apply:
      tags: 'user'

- name: 'Install freestanding config dropins for {{ editor }}'
  loop: '{{ role_editor_configs }}'
  ansible.builtin.copy:
    src: 'editor_configs/{{ editor }}/{{ item }}'
    dest: '{{ configs_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'
