---
- name: 'install basic development tools'
  when: 'install_packages'
  become: true
  package:
    state: 'present'
    name:
      - 'binutils'

      # Basic C toolchain. it is in base, as it is used for numerous things,
      # not only for C development.
      - 'm4'
      - 'make'
      - 'autoconf'
      - 'automake'
      - 'cmake'
      - 'pkgconf'
      - 'gcc'

      # Versioning and patching tools.
      - 'git'
      - 'diffutils'
      - 'patch'

      # These libs are used for XML processing.
      #
      # Though they are usually installed as dependencies, we install them
      # explicitly to know that we have xmllint and xsltproc tools in the system.
      # These are needed for poor man's XML autoformatting hotkeys in editors.
      - 'libxml2'
      - 'libxslt'

- name: 'install drop-ins for shells'
  loop: '{{ user_config["shells"] | dict2items }}'
  copy:
    src: 'shell_dropins/{{ item["key"] }}/'
    dest: '{{ user_config["home_dir"] }}/{{ item["value"]["config_dropins_dir"] }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- name: 'install templated profile drop-ins'
  loop:
    - '10_01_dev_base_xmllint'
  template:
    src: 'profile_dropins/{{ item }}.j2'
    dest: '{{ user_config["home_dir"] }}/{{ user_config["profile_dropins_dir"] }}/{{ item }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- name: 'install drop-ins for editors'
  loop: '{{ user_config["editors"] | dict2items | map(attribute = "key") }}'
  loop_control:
    loop_var: 'editor_item'
  vars:
    editor: '{{ editor_item }}'
  include_tasks:
    file: 'editor_config.yml'
