---
- name: 'Store editor-related settings'
  ansible.builtin.set_fact:
    plugins_dir: '{{ user_config["home_dir"] }}/{{ user_config["editors"][editor]["plugins_dir"] }}'
    configs_dir: '{{ user_config["home_dir"] }}/{{ user_config["editors"][editor]["config_dropins_dir"] }}'
    role_editor_plugins: '{{ devel_extra_editor_plugins[editor] }}'
    role_editor_configs: '{{ devel_extra_editor_plugins[editor] }}'

- name: 'Install plugins for {{ editor }}'
  loop: '{{ role_editor_plugins | dict2items | map(attribute="key") }}'
  vars:
    plugin: '{{ item }}'
  ansible.builtin.include_tasks:
    file: '{{ editor }}_plugin.yml'
    apply:
      tags: 'user'
