---
- name: 'install extra development tools'
  when: 'install_packages'
  become: true
  package:
    state: 'present'
    name:
      # Basic debugging tools.
      - 'gdb'
      - 'valgrind'

      # VCS stuff that is unlikely to be needed.
      - 'git-delta'
      - 'subversion'
      - 'mercurial'

      # Mostly used for package building, specifically, AUR packages.
      - 'fakeroot'

      # Heavyweight stuff.
      - 'podman'
      - 'buildah'
      - 'skopeo'

      # XXX: here we intentionally do not install any backend for Vagrant.
      # The easiest to use (and most probable) backend is a Virtualbox, however,
      # in Arch repos, it comes only in full form (headless one is only in AUR).
      #
      # Installing full VBox version is an overkill at this stage, so we either
      # wait for GUI roles to run (if any) or let the user to opt-in for this
      # bloatware explicitly. Finally, the user may choose to install another
      # hypervisor manually.
      - 'vagrant'

      # Cloud clients.
      - 'kubectl'

      # Database clients.
      - 'mariadb-clients'
      - 'postgresql-libs'

- name: 'install drop-ins for shells'
  loop: '{{ user_config["shells"] | dict2items }}'
  copy:
    src: 'shell_dropins/{{ item["key"] }}/'
    dest: '{{ user_config["home_dir"] }}/{{ item["value"]["dropins_dir"] }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
