---
- name: 'find plugin config for {{ plugin }}'
  ansible.builtin.set_fact:
    plugin_config: '{{ role_editor_plugins[plugin] }}'
    plugin_dir: '{{ plugins_dir }}/{{ plugin }}'

- name: 'download {{ plugin }} plugin'
  ansible.builtin.git:
    repo: '{{ plugin_config.repo }}'
    dest: '{{ plugin_dir }}'
    depth: 1
    force: true

- name: 'install {{ plugin }} plugin config'
  when: 'plugin_config.requires_config'
  ansible.builtin.copy:
    src: 'editor_configs/vim/{{ plugin }}.vim'
    dest: '{{ configs_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0644

- ansible.builtin.include_tasks:
    file: 'vim_plugins/{{ plugin }}_build.yml'
    apply:
      tags: 'user'
  when: 'plugin_config.requires_build'
