---
- name: 'install lightdm packages'
  become: true
  loop:
    - 'lightdm'
    - 'lightdm-slick-greeter'
    - 'light-locker'
  package:
    name: '{{ item }}'
    state: 'present'

- name: 'install lightdm configuration'
  become: true
  loop:
    - 'lightdm.conf'
    - 'users.conf'
  copy:
    src: '{{ item }}'
    dest: '/etc/lightdm/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: 'install lightdm templates'
  become: true
  loop:
    - 'slick-greeter.conf'
  template:
    src: '{{ item }}.j2'
    dest: '/etc/lightdm/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: 'enable lightdm service'
  become: true
  service:
    name: 'lightdm'
    enabled: true
