---
- name: 'Check that role supports target OS'
  when: 'ansible_os_family not in ["Archlinux"]'
  tags: 'user'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      target OS family is: {{ ansible_os_family }}.

- name: 'Install extra CLI tools'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'moreutils'
      - 'ripgrep'
      - 'fd'
      - 'fzf'
      - 'bat'
      - 'jq'
      - 'yq'
      - 'wget'
      - 'lynx'

- name: 'Install profile drop-ins'
  tags: 'user'
  ansible.builtin.copy:
    src: 'profile_dropins/'
    dest: '{{ user_config.home_dir }}/{{ user_config.profile_dropins_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'

- name: 'Install drop-ins for shells'
  tags: 'user'
  loop: '{{ user_config.shells | dict2items }}'
  ansible.builtin.copy:
    src: 'shell_dropins/{{ item.key }}/'
    dest: '{{ user_config.home_dir }}/{{ item.value.config_dropins_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'

- name: 'Install drop-ins for editors'
  tags: 'user'
  loop: '{{ user_config.editors | dict2items | map(attribute="key") }}'
  loop_control:
    loop_var: 'editor_item'
  vars:
    editor: '{{ editor_item }}'
  ansible.builtin.include_tasks:
    file: 'editor_config.yml'
    apply:
      tags: 'user'
