---
- name: 'Create youcompleteme build directory'
  ansible.builtin.file:
    path: '{{ plugin_dir }}/build'
    state: 'directory'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0755

- name: 'Prepare plugin for build'
  ansible.builtin.command: 'cmake -G "Unix Makefiles" . {{ plugin_dir }}/third_party/ycmd/cpp'
  args:
    chdir: '{{ plugin_dir }}/build'

- name: 'Build youcompleteme plugin'
  ansible.builtin.command: 'cmake --build . --target ycm_core'
  args:
    chdir: '{{ plugin_dir }}/build'

- name: 'Install watchdog library'
  ansible.builtin.copy:
    remote_src: true
    src: '{{ plugin_dir }}/third_party/ycmd/third_party/watchdog_deps/watchdog/src/watchdog'
    dest: '{{ plugin_dir }}/third_party/ycmd/third_party/watchdog_deps/watchdog/build/lib3/'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0755

- name: 'Youcompleteme language support - Golang'
  when: '"devel-go" in user_config["toolchains"]'
  ansible.builtin.command: 'go install golang.org/x/tools/gopls@v0.7.1'
  environment:
    GO111MODULE: 'on'
    GOPATH: '{{ plugin_dir }}/third_party/ycmd/third_party/go'
    GOBIN: '{{ plugin_dir }}/third_party/ycmd/third_party/go/bin'

# XXX: here we diverge from YCM installation guide, which suggests installing
# whole toolchain into the temporary directory and then copy it into YCM dir.
# This is done to avoid syncing YCM with each rustup update - we just point YCM
# to the user's default rustup home, assuming that the toolchain is present.
- name: 'Youcompleteme language support - Rust'
  when: '"devel-rust" in user_config["toolchains"]'
  block:
    - name: 'YCM Rust - find default toolchain'
      ansible.builtin.set_fact:
        rustup_default_toolchain: >-
          {{
             user_config["toolchains"]["devel-rust"]["rustup_toolchains"] |
             selectattr("default", "defined") |
             selectattr("default") |
             map(attribute = "name") |
             first
          }}

    - name: 'YCM Rust - integrate YCM with Rust toolchain'
      when:
      ansible.builtin.file:
        path: '{{ plugin_dir }}/third_party/ycmd/third_party/rust-analyzer'
        src: '{{ user_config["home_dir"] }}/.rustup/toolchains/{{ rustup_default_toolchain }}'
        state: 'link'

- name: 'Remove youcompleteme build directory'
  ansible.builtin.file:
    path: '{{ plugin_dir }}/build'
    state: 'absent'
