---
vim_pathogen_url: https://tpo.pe/pathogen.vim

vim_configs_plugins:
  nerdtree:
    repo: https://github.com/scrooloose/nerdtree
    requires_build: false
    requires_config: true

  syntastic:
    repo: https://github.com/vim-syntastic/syntastic
    requires_build: false
    requires_config: false

  fugitive:
    repo: https://github.com/tpope/vim-fugitive
    requires_build: false
    requires_config: true

  mru:
    repo: https://github.com/vim-scripts/mru.vim
    requires_build: false
    requires_config: true

  commandt:
    repo: https://github.com/wincent/Command-T
    requires_build: true
    requires_config: true

  youcompleteme:
    repo: https://github.com/Valloric/YouCompleteMe
    requires_build: true
    requires_config: true

  rust:
    repo: https://github.com/rust-lang/rust.vim
    requires_build: false
    requires_config: true

  rustdoc:
    repo: https://github.com/rhysd/rust-doc.vim
    requires_build: false
    requires_config: false

