---
- name: 'install multimedia tools'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'ffmpeg'
      - 'flac'
      - 'audacity'
      - 'gimp'
