---
- name: 'install bash'
  when: 'install_packages'
  become: true
  package:
    name: 'bash'
    state: 'present'

- name: 'get home dir of {{ user }}'
  getent:
    database: 'passwd'
    key: '{{ user }}'
    split: ':'

- name: 'store home dir of {{ user }}'
  set_fact:
    home_dir: '{{ getent_passwd[user][4] }}'

- name: 'clean managed drop-ins directory'
  file:
    path: '{{ home_dir }}/.bashrc.d'
    state: 'absent'

- name: 'ensure drop-ins directories exist'
  loop:
    - '{{ home_dir }}/.bashrc.d'
    - '{{ home_dir }}/.bashrc.d-unmanaged'
  file:
    path: '{{ item }}'
    owner: '{{ user }}'
    group: '{{ user }}'
    state: 'directory'
    mode: 0755

- name: 'install basic .bashrc'
  template:
    src: 'bashrc.j2'
    dest: '{{ home_dir }}/.bashrc'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644

- name: 'install .bash_profile'
  copy:
    src: 'bash_profile'
    dest: '{{ home_dir }}/.bash_profile'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644
