---
user_config:
  name: 'qazer'
  home_dir: '/home/qazer'

features: {
  # Uncomment to enable support for different software.
  #
  # dev:
  #
  #   # Enables hotkeys for Java-related GUI tools.
  #   - 'java'
}

system:
  hidpi: false

  gui:
    dm: 'lightdm'

install_packages: true
