VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|
    if VAGRANT_COMMAND == "ssh"
        config.ssh.username = 'qazer'
    end

    config.vm.box = "almalinux/8"

    config.vm.network :forwarded_port, guest: 22, host: 2220, id: "ssh"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end

    config.vm.provision "shell", inline: <<-SHELL
        getent passwd qazer &> /dev/null || adduser -m qazer
        echo "qazer ALL=NOPASSWD:ALL" > /etc/sudoers.d/qazer
        mkdir -p -m 0700 /home/qazer/.ssh
        cp /home/vagrant/.ssh/authorized_keys /home/qazer/.ssh/
        chown -R qazer.qazer /home/qazer/.ssh

        # XXX: we have to test against specific Python version, as newer ones
        # are not guaranteed to work well with yum tasks on RHEL8.
        #
        # See https://github.com/ansible/ansible/issues/83357
        yum install -y python36
    SHELL

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../install.yml"

        # XXX: run the wrapper to use last Ansible version compatible with RHEL8.
        ansible.playbook_command = "../../ansible-playbook"

        ansible.groups = {
            "servers": ["default"]
        }
    end
end
