---
- name: 'install bash'
  when: 'install_packages'
  become: true
  package:
    name: 'bash'
    state: 'present'

- name: 'clean managed drop-ins directory'
  file:
    path: '{{ user_config["home_dir"] }}/{{ shell_config["config_dropins_dir"] }}'
    state: 'absent'

- name: 'ensure drop-ins directories exist'
  file:
    path: '{{ user_config["home_dir"] }}/{{ shell_config["config_dropins_dir"] }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755

- name: 'install basic .bashrc'
  template:
    src: 'bashrc.j2'
    dest: '{{ user_config["home_dir"] }}/.bashrc'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- name: 'install .bash_profile'
  copy:
    src: 'bash_profile'
    dest: '{{ user_config["home_dir"] }}/.bash_profile'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- name: 'install basic drop-ins'
  copy:
    src: 'dropins/'
    dest: '{{ user_config["home_dir"] }}/{{ shell_config["config_dropins_dir"] }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644

- name: 'install templated basic drop-ins'
  loop:
    - '00_03_arch_utils'
  template:
    src: 'dropins/{{ item }}.j2'
    dest: '{{ user_config["home_dir"] }}/{{ shell_config["config_dropins_dir"] }}/{{ item }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
