---
- name: 'Fail if role does not support target OS'
  when: 'ansible_os_family not in ["Archlinux", "RedHat"]'
  tags: 'user'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      target OS family is: {{ ansible_os_family }}.

- name: 'Install bash'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    name: 'bash'
    state: 'present'

- name: 'Clean managed drop-ins directory'
  when: 'clean_configs in ["safe", "all"]'
  tags: 'user'
  ansible.builtin.file:
    path: '{{ user_config.home_dir }}/{{ shell_config.config_dropins_dir }}'
    state: 'absent'

- name: 'Ensure drop-ins directories exist'
  tags: 'user'
  ansible.builtin.file:
    path: '{{ user_config.home_dir }}/{{ shell_config.config_dropins_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: 'directory'
    mode: '0755'

- name: 'Install basic .bashrc'
  tags: 'user'
  ansible.builtin.template:
    src: 'bashrc.j2'
    dest: '{{ user_config.home_dir }}/.bashrc'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'

- name: 'Install .bash_profile'
  tags: 'user'
  ansible.builtin.copy:
    src: 'bash_profile'
    dest: '{{ user_config.home_dir }}/.bash_profile'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'

- name: 'Install basic drop-ins'
  tags: 'user'
  ansible.builtin.copy:
    src: 'dropins/'
    dest: '{{ user_config.home_dir }}/{{ shell_config.config_dropins_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'

- name: 'Prepare vars for PS1 configuration'
  tags: 'user'
  ansible.builtin.set_fact:
    host_role: >-
      {{
        "server" if "servers" in groups
        else (
          "device" if "devices" in groups
          else (
            "desktop" if "desktops" in groups
            else "unknown"
          )
        )
      }}
    user_role: >-
      {{
        "superuser" if user_name == "root"
        else "unprivileged"
      }}

- name: 'Install templated basic drop-ins'
  tags: 'user'
  loop:
    - '00_01_bash_ps_vars'
    - '00_03_distro_utils'
  ansible.builtin.template:
    src: 'dropins/{{ item }}.j2'
    dest: '{{ user_config.home_dir }}/{{ shell_config.config_dropins_dir }}/{{ item }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'
