---
install_packages: true

toolchain_config:
  rustup_toolchains:
    - name: 'stable-x86_64-unknown-linux-gnu'
      default: true
    - name: 'nightly-x86_64-unknown-linux-gnu'

  cargo_plugins:
    - 'cargo-expand'
