---
- name: 'install gtk3'
  when: 'install_packages'
  become: true
  package:
    name: 'gtk3'
    state: 'present'

- name: 'get home dir of {{ user }}'
  getent:
    database: 'passwd'
    key: '{{ user }}'
    split: ':'

- name: 'store home dir of {{ user }}'
  set_fact:
    home_dir: '{{ getent_passwd[user][4] }}'

- name: 'ensure gkt3 config directory exists'
  file:
    path: '{{ home_dir }}/.config/gtk-3.0'
    owner: '{{ user }}'
    group: '{{ user }}'
    state: 'directory'
    mode: 0755

- name: 'install gtk3 configuration'
  copy:
    src: 'gtk.css'
    dest: '{{ home_dir }}/.config/gtk-3.0/gtk.css'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0644
