---
- name: 'install golang toolchain'
  become: true
  package:
    name: 'go'
    state: 'present'

- name: 'ensure GOPATH exists'
  tags: 'user'
  file:
    path: '{{ user_config["home_dir"] }}/{{ toolchain_config["gopath"] }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755

- name: 'install templated profile drop-ins'
  tags: 'user'
  loop:
    - '15_01_go_gopath'
  template:
    src: 'profile_dropins/{{ item }}.j2'
    dest: '{{ user_config["home_dir"] }}/{{ user_config["profile_dropins_dir"] }}/{{ item }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    mode: 0644
