---
- name: 'install golang toolchain'
  when: 'install_packages'
  become: true
  package:
    name: 'go'
    state: 'present'

- name: 'ensure GOPATH exists'
  file:
    path: '{{ user_config["home_dir"] }}/{{ toolchain_config["gopath"] }}'
    owner: '{{ user_config["name"] }}'
    group: '{{ user_config["name"] }}'
    state: 'directory'
    mode: 0755
