---
user_config:
  name: 'qazer'
  home_dir: '/home/qazer'

install_packages: true

# Only nightly currently has rust-analyzer.
rustup_toolchain: 'nightly-x86_64-unknown-linux-gnu'



# Here be dragons (till the end of the file)!
#
# You don't wish to override these defaults unless you explicitly know
# what do you do. Touch this only in extreme cases, e.g. some plugin moves
# to another repo, or adds a build step, etc.

vim_extra_plugins:
  youcompleteme:
    repo: https://github.com/Valloric/YouCompleteMe
    requires_build: true
    requires_config: true

  rust:
    repo: https://github.com/rust-lang/rust.vim
    requires_build: false
    requires_config: true

  rustdoc:
    repo: https://github.com/rhysd/rust-doc.vim
    requires_build: false
    requires_config: false
