---
user_config:
  name: 'qazer'
  home_dir: '/home/qazer'
  downloads_dir: '/home/qazer/misc/downloads'

app_config:
  terminal: 'xterm'
  editor: 'vi'

install_packages: true

force_clean_configs: false
