---
- name: 'Fail if role does not support target OS'
  when: 'ansible_os_family not in ["Archlinux", "RedHat", "PureOS"]'
  tags: 'user'
  ansible.builtin.fail:
    msg: >-
      This role does not yet support target distribution;
      target OS family is: {{ ansible_os_family }}.

- name: 'Install network administration tools'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name: '{{ tools_admin_network_packages[ansible_os_family] }}'

- name: 'Install GUI network administration tools'
  when: '"gui" in user_config'
  become: true
  become_user: 'root'
  ansible.builtin.package:
    state: 'present'
    name:
      - 'wireshark-qt'

- name: 'Install drop-ins for shells'
  tags: 'user'
  loop: '{{ user_config.shells | dict2items }}'
  ansible.builtin.copy:
    src: 'shell_dropins/{{ item.key }}/'
    dest: '{{ user_config.home_dir }}/{{ item.value.config_dropins_dir }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: '0644'
