---
- name: 'check if xfce-panel is running'
  command: 'pgrep xfce4-panel'
  register: 'panel_test'
  failed_when: 'panel_test.rc >= 2'
  listen: 'reconfigure xfce-panel'

- name: 'check if xfconfd is running'
  command: 'pgrep xfconfd'
  register: 'xfconfd_test'
  failed_when: 'xfconfd_test.rc >= 2'
  listen: 'reconfigure xfce-panel'

- name: 'restart panel with new settings'
  shell: 'killall xfconfd && xfce4-panel -r'
  when: 'panel_test.rc == 0 and xfconfd_test.rc == 0'
  listen: 'reconfigure xfce-panel'

